CREATE TABLE `tenant` (
  `TENANT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TENANT_NAME` varchar(20) NOT NULL DEFAULT '',
  `TENANT_DESCRIPTION` varchar(150) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT 'ACTIVE',
  `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TENANT_TYPE` varchar(45) NOT NULL DEFAULT 'DEFAULT',
  PRIMARY KEY (`TENANT_ID`),
  UNIQUE KEY `UNQ_TENANTNAME` (`TENANT_NAME`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
